kind: pipeline
name: default

steps:
- name: lint
  image: node
  volumes:
  - name: node
    path: /tmp/node
  commands:
  - npm ci
  - npm run lint
  - npm audit
  when:
    event:
    - push

- name: build
  image: node
  volumes:
  - name: node
    path: /tmp/node
  commands:
  - npm run build
  when:
    event:
    - push

- name: commitlint
  image: node
  volumes:
  - name: node
    path: /tmp/node
  commands:
  - npm run lint:commit
  when:
    branch:
    - master
    - develop
    event:
    - push


- name: release
  image: node
  volumes:
  - name: node
    path: /tmp/node
  commands:
  - npm run release
  when:
    branch:
    - master
    event:
    - push