kind: pipeline
name: default

steps:
- name: lint
  image: node
  volumes:
  - name: node
    path: /tmp/node
  commands:
  - npm ci
  - npm run lint
  - npm audit
  event:
    include:
    - push
    exclude:
    - pull_request

- name: build
  image: node
  volumes:
  - name: node
    path: /tmp/node
  commands:
  - npm run build
  event:
    include:
    - push
    exclude:
    - pull_request

- name: commitlint
  image: node
  volumes:
  - name: node
    path: /tmp/node
  commands:
  - npm run lint:commit
  when:
    branch:
    - master
    - develop
    event:
      include:
      - push
      exclude:
      - pull_request


- name: release
  image: node
  volumes:
  - name: node
    path: /tmp/node
  commands:
  - npm run release
  when:
    branch:
    - master
    event:
      include:
        - push